language: pt
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 2
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "neuralmind/bert-base-portuguese-cased"
  cache_dir: null
- name: DIETClassifier
  epochs: 100
  random_seed: 42
  constrain_similarities: true
  batch_size: 64
  learning_rate: 0.005
  number_of_transformer_layers: 2
  transformer_size: 256
  dropout_rate: 0.3
  weight_sparsity: 0.1
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
assistant_id: 20250512-225924-internal-HUD
