app = "nlu-escuta-ia"

primary_region = "gru"

[build]

[env]
PORT = "5005"

[[services]]
internal_port = 5005
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
interval = "30s"
timeout = "5s"
grace_period = "20s"
restart_limit = 0
